name: ci
on: [push, pull_request]

env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  test:
    name: Build and test (${{ matrix.version }})
    runs-on: ubuntu-latest
    container: ghcr.io/verdiwm/ci-image:latest
    strategy:
      fail-fast: false
      matrix:
        version:
          - "1_22"
          - "1_23"
          - "1_24"
          - "1_25"
          - "1_26"
          - "1_27"
          - "1_28"
    steps:
      - uses: actions/checkout@v4

      - name: Check clippy
        run: cargo clippy --no-default-features --features ${{ matrix.version }},tokio,tracing,helper --all-targets --workspace

      - name: Run tests
        run: cargo test --no-default-features --features ${{ matrix.version }},tokio,tracing,helper --all-targets --workspace

  test-multiple-versions:
    name: Test multiple versions fail
    runs-on: ubuntu-latest
    container: ghcr.io/verdiwm/ci-image:latest
    steps:
      - uses: actions/checkout@v4

      - name: Verify multiple versions error
        run: |
          set +e
          cargo check --all-features
          if [ $? -eq 0 ]; then
            echo "Build succeeded when it should have failed"
            exit 1
          fi

  test-debian-stable:
    name: Build on Debian stable
    runs-on: ubuntu-latest
    container: rust:slim
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y pkg-config libinput-dev

      - name: Build
        run: cargo build --features tokio,tracing,helper

  fmt:
    name: Check Formatting
    runs-on: ubuntu-latest
    container: ghcr.io/verdiwm/ci-image:latest
    steps:
      - uses: actions/checkout@v4
      - name: Run formatter
        run: cargo fmt --check
